Repository rjsturing/rancid-tomatillos, pull requests merged in 2023-12, with the labels that each got.

#20 feat: Main page layout and content
  src/App.js
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.css
  src/Card/Card.js
  src/Card/Card.test.js
  src/Movies/Movies.css
  src/Movies/Movies.js
  src/Movies/Movies.test.js
  src/index.js
  src/mock-data.js
Labels: user story

#21 feat: Single movie page layout and content
  src/App/App.js
  src/Card/Card.js
  src/MovieDetail/MovieDetail.css
  src/MovieDetail/MovieDetail.js
  src/Movies/Movies.js
Labels: user story

#22 Feature/setup apis
  src/App/App.js
  src/Card/Card.js
  src/MovieDetail/MovieDetail.js
  src/Movies/Movies.js
Labels: user story

#23 feat: Error handling
  src/App/App.css
  src/App/App.js
Labels: user story

#41 feature: Implement Cypress testing
  cypress.config.js
  cypress/e2e/homepage_spec.cy.js
  cypress/e2e/moviedetail_spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: setup

#43 fix: Update initial state for movies to be empty array
  src/App/App.js
  src/Movies/Movies.js
Labels: bug, task

#44 refactor: Add apiCalls.js file for separation of concerns
  src/App/App.js
  src/apiCalls.js
Labels: enhancement, task

#38 refactor: Remove hard to understand inline CSS
  src/App/App.css
  src/App/App.js
Labels: needs review

#46 Feature/Setup React Router
  package-lock.json
  package.json
  src/index.js
Labels: task

#48 Bug/detail rendering
  src/App/App.css
  src/App/App.js
  src/MovieDetail/MovieDetail.css
Labels: bug, needs review

#50 Feature/Setup dynamic routing
  src/App/App.css
  src/App/App.js
  src/MovieDetail/MovieDetail.css
  src/MovieDetail/MovieDetail.js
  src/Movies/Movies.css
  src/Movies/Movies.js
  src/apiCalls.js
Labels: user story

#57 test: Add Cypress tests for main page
  cypress/e2e/homepage_spec.cy.js
  cypress/fixtures/mock-data.json
Labels: test

#56 Refactor/movie css
  public/index.html
  public/tomatillo-icon.png
  src/App/App.css
  src/App/App.js
  src/Card/Card.css
  src/Card/Card.js
  src/Fonts/Fonts.css
  src/Fonts/elMariachi.otf
  src/MovieDetail/MovieDetail.css
  src/MovieDetail/MovieDetail.js
  src/index.js
  src/logo.svg
Labels: task

#61 fix: Make error messaging clear automatically if there is no more error
  src/App/App.js
  src/Movies/Movies.js
Labels: bug

#60 feat: Add PropTypes functionality to the project
  package-lock.json
  package.json
  public/index.html
  src/Card/Card.js
  src/Movies/Movies.js
Labels: task

#64 fix: Address module script console error
  public/index.html
Labels: bug

#65 feat: Make main page responsive for several breakpoints
  src/App/App.css
  src/Movies/Movies.css
Labels: user story

#71 fix: Update main page Cypress tests
  cypress/e2e/homepage_spec.cy.js
Labels: task, test

#69 feat: Make detail page responsive for smaller breakpoint
  src/App/App.css
  src/App/App.js
  src/MovieDetail/MovieDetail.css
  src/MovieDetail/MovieDetail.js
Labels: enhancement, task

#62 test: Add Cypress tests for Movie Details pages
  cypress/e2e/homepage_spec.cy.js
  cypress/e2e/moviedetail_spec.cy.js
  cypress/fixtures/mock-data.json
  cypress/fixtures/mock-movie-0.json
  cypress/fixtures/mock-movie-1.json
  src/mock-data.js
Labels: task

#68 docs: Update README
  README.md
Labels: documentation

#73 refactor: Clean up code formatting, extraneous files, etc
  cypress.config.js
  cypress/e2e/errorhandling_spec.cy.js
  cypress/e2e/homepage_spec.cy.js
  cypress/e2e/moviedetail_spec.cy.js
  package-lock.json
  package.json
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.css
  src/Card/Card.js
  src/Card/Card.test.js
  src/Fonts/Fonts.css
  src/MovieDetail/MovieDetail.css
  src/Movies/Movies.css
  src/Movies/Movies.js
  src/Movies/Movies.test.js
  src/NotFound/NotFound.css
  src/NotFound/NotFound.js
  src/apiCalls.js
  src/index.css
  src/index.js
  src/reportWebVitals.js
Labels: enhancement, task
